/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PaymentsRefundPolicyRouteImport } from './routes/payments-refund-policy'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as DisclaimerCookiePolicyRouteImport } from './routes/disclaimer-cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareerRouteImport } from './routes/career'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as AdminNewLeadsRouteImport } from './routes/admin.new-leads'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEnquiryLeadsRouteImport } from './routes/admin.enquiry-leads'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminChangePasswordRouteImport } from './routes/admin.change-password'
import { Route as AdminCallbackLeadsRouteImport } from './routes/admin.callback-leads'

const TermsConditionsRoute = TermsConditionsRouteImport.update({
  id: '/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRefundPolicyRoute = PaymentsRefundPolicyRouteImport.update({
  id: '/payments-refund-policy',
  path: '/payments-refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerCookiePolicyRoute = DisclaimerCookiePolicyRouteImport.update({
  id: '/disclaimer-cookie-policy',
  path: '/disclaimer-cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewLeadsRoute = AdminNewLeadsRouteImport.update({
  id: '/admin/new-leads',
  path: '/admin/new-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnquiryLeadsRoute = AdminEnquiryLeadsRouteImport.update({
  id: '/admin/enquiry-leads',
  path: '/admin/enquiry-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChangePasswordRoute = AdminChangePasswordRouteImport.update({
  id: '/admin/change-password',
  path: '/admin/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCallbackLeadsRoute = AdminCallbackLeadsRouteImport.update({
  id: '/admin/callback-leads',
  path: '/admin/callback-leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/disclaimer-cookie-policy': typeof DisclaimerCookiePolicyRoute
  '/faqs': typeof FaqsRoute
  '/payments-refund-policy': typeof PaymentsRefundPolicyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success': typeof SuccessRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/admin/callback-leads': typeof AdminCallbackLeadsRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enquiry-leads': typeof AdminEnquiryLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new-leads': typeof AdminNewLeadsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/disclaimer-cookie-policy': typeof DisclaimerCookiePolicyRoute
  '/faqs': typeof FaqsRoute
  '/payments-refund-policy': typeof PaymentsRefundPolicyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success': typeof SuccessRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/admin/callback-leads': typeof AdminCallbackLeadsRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enquiry-leads': typeof AdminEnquiryLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new-leads': typeof AdminNewLeadsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/disclaimer-cookie-policy': typeof DisclaimerCookiePolicyRoute
  '/faqs': typeof FaqsRoute
  '/payments-refund-policy': typeof PaymentsRefundPolicyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success': typeof SuccessRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/admin/callback-leads': typeof AdminCallbackLeadsRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enquiry-leads': typeof AdminEnquiryLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new-leads': typeof AdminNewLeadsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/career'
    | '/contact'
    | '/disclaimer-cookie-policy'
    | '/faqs'
    | '/payments-refund-policy'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/success'
    | '/terms-conditions'
    | '/admin/callback-leads'
    | '/admin/change-password'
    | '/admin/dashboard'
    | '/admin/enquiry-leads'
    | '/admin/login'
    | '/admin/new-leads'
    | '/services/$slug'
    | '/admin/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/career'
    | '/contact'
    | '/disclaimer-cookie-policy'
    | '/faqs'
    | '/payments-refund-policy'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/success'
    | '/terms-conditions'
    | '/admin/callback-leads'
    | '/admin/change-password'
    | '/admin/dashboard'
    | '/admin/enquiry-leads'
    | '/admin/login'
    | '/admin/new-leads'
    | '/services/$slug'
    | '/admin'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/career'
    | '/contact'
    | '/disclaimer-cookie-policy'
    | '/faqs'
    | '/payments-refund-policy'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/success'
    | '/terms-conditions'
    | '/admin/callback-leads'
    | '/admin/change-password'
    | '/admin/dashboard'
    | '/admin/enquiry-leads'
    | '/admin/login'
    | '/admin/new-leads'
    | '/services/$slug'
    | '/admin/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CareerRoute: typeof CareerRoute
  ContactRoute: typeof ContactRoute
  DisclaimerCookiePolicyRoute: typeof DisclaimerCookiePolicyRoute
  FaqsRoute: typeof FaqsRoute
  PaymentsRefundPolicyRoute: typeof PaymentsRefundPolicyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuccessRoute: typeof SuccessRoute
  TermsConditionsRoute: typeof TermsConditionsRoute
  AdminCallbackLeadsRoute: typeof AdminCallbackLeadsRoute
  AdminChangePasswordRoute: typeof AdminChangePasswordRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEnquiryLeadsRoute: typeof AdminEnquiryLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewLeadsRoute: typeof AdminNewLeadsRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-conditions': {
      id: '/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof TermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments-refund-policy': {
      id: '/payments-refund-policy'
      path: '/payments-refund-policy'
      fullPath: '/payments-refund-policy'
      preLoaderRoute: typeof PaymentsRefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer-cookie-policy': {
      id: '/disclaimer-cookie-policy'
      path: '/disclaimer-cookie-policy'
      fullPath: '/disclaimer-cookie-policy'
      preLoaderRoute: typeof DisclaimerCookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new-leads': {
      id: '/admin/new-leads'
      path: '/admin/new-leads'
      fullPath: '/admin/new-leads'
      preLoaderRoute: typeof AdminNewLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/enquiry-leads': {
      id: '/admin/enquiry-leads'
      path: '/admin/enquiry-leads'
      fullPath: '/admin/enquiry-leads'
      preLoaderRoute: typeof AdminEnquiryLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/change-password': {
      id: '/admin/change-password'
      path: '/admin/change-password'
      fullPath: '/admin/change-password'
      preLoaderRoute: typeof AdminChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/callback-leads': {
      id: '/admin/callback-leads'
      path: '/admin/callback-leads'
      fullPath: '/admin/callback-leads'
      preLoaderRoute: typeof AdminCallbackLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CareerRoute: CareerRoute,
  ContactRoute: ContactRoute,
  DisclaimerCookiePolicyRoute: DisclaimerCookiePolicyRoute,
  FaqsRoute: FaqsRoute,
  PaymentsRefundPolicyRoute: PaymentsRefundPolicyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuccessRoute: SuccessRoute,
  TermsConditionsRoute: TermsConditionsRoute,
  AdminCallbackLeadsRoute: AdminCallbackLeadsRoute,
  AdminChangePasswordRoute: AdminChangePasswordRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEnquiryLeadsRoute: AdminEnquiryLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNewLeadsRoute: AdminNewLeadsRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
