import {
  Search, Share2, Code2, Target, Sparkles, Megaphone, MapPin, Brain,
  ShoppingBag, Star,
  type LucideIcon,
} from "lucide-react";

export type Service = {
  slug: string;
  title: string;
  short: string;
  icon: LucideIcon;
  category: string;
  tagline: string;
  headline: string;
  overview: string;
  overviewExtra?: string;
  included: string[];
  why: string;
  benefits: { title: string; desc: string }[];
  whyChoose: { title: string; desc: string }[];
  process: { title: string; desc: string }[];
  stats: { label: string; value: number; suffix?: string }[];
  faqs: { q: string; a: string }[];
};

const standardProcess = [
  { title: "Discovery", desc: "Deep-dive into your brand, audience, competitors and current performance." },
  { title: "Strategy", desc: "Custom roadmap with channels, KPIs, positioning and timeline." },
  { title: "Planning", desc: "Calendars, creative briefs, asset lists and approval workflows." },
  { title: "Execution", desc: "Launch campaigns, content, automations and optimizations." },
  { title: "Optimization", desc: "Weekly iteration — kill what's not working, double down on what is." },
  { title: "Reporting", desc: "Transparent monthly dashboards tied to real business outcomes." },
];

const standardWhyChoose = [
  { title: "Senior In-House Team", desc: "Strategists, designers, developers and media buyers — never outsourced." },
  { title: "Results-First Approach", desc: "Every initiative tied to leads, revenue or measurable brand growth." },
  { title: "Transparent Reporting", desc: "Live dashboards, clear KPIs, no black boxes — ever." },
  { title: "Fast, Responsive Support", desc: "Average response time under 30 minutes across all channels." },
  { title: "Industry Expertise", desc: "Proven playbooks across startups, local businesses, e-commerce and enterprises." },
  { title: "Long-Term Partnership", desc: "96% client retention — we grow with you, not just for you." },
];

export const services: Service[] = [
  {
    slug: "social-media-management",
    title: "Social Media Management",
    short: "Build a brand people follow, trust and buy from.",
    icon: Share2,
    category: "Marketing",
    tagline: "Social that sells — without feeling salesy.",
    headline: "Social Media Marketing That Builds Brand Awareness & Engagement",
    overview:
      "As a results-driven social media marketing agency, we help brands build a strong digital presence through creative content, performance-focused strategies, and consistent audience engagement.",
    overviewExtra:
      "We create customized social media strategies for startups, local businesses, e-commerce brands and growing enterprises to improve reach, engagement, lead generation, and long-term business growth.",
    included: [
      "Social Media Strategy & Planning",
      "Instagram & Facebook Management",
      "Reels & Short-Form Video Production",
      "Creative Post Designing",
      "Content Calendar Planning",
      "Brand Storytelling & Content Writing",
      "Community Management & Engagement",
      "Influencer & Collaboration Campaigns",
      "Social Media Performance Analysis",
      "Monthly Insights & Reporting",
    ],
    why: "Modern customers research you on social before they ever click. We make sure they find a brand worth following — and buying from.",
    benefits: [
      { title: "Stronger Brand Visibility", desc: "Show up consistently where your audience already spends time." },
      { title: "Higher Engagement", desc: "Comments, shares and DMs that translate into real conversations." },
      { title: "Qualified Lead Flow", desc: "Organic + paid working together to fill your pipeline." },
      { title: "Customer Trust", desc: "Become the recognized voice in your category." },
      { title: "Content That Converts", desc: "Scroll-stopping reels, carousels and posts engineered to perform." },
      { title: "Data-Driven Growth", desc: "Monthly insights that improve every cycle." },
    ],
    whyChoose: standardWhyChoose,
    process: standardProcess,
    stats: [
      { label: "Engagement Lift", value: 240, suffix: "%" },
      { label: "Followers Grown", value: 350000, suffix: "+" },
      { label: "Reels Produced", value: 2100, suffix: "+" },
    ],
    faqs: [
      { q: "Which platforms do you manage?", a: "Instagram, Facebook, LinkedIn, YouTube and X — based on where your audience actually is." },
      { q: "Do you create the content and creatives?", a: "Yes. Scripting, design, photography, videography, editing and copywriting are all done in-house." },
      { q: "How many posts do I get per month?", a: "Plans typically include 12–20 static posts plus 6–10 reels, with custom packages for higher volume needs." },
      { q: "Will I get a content calendar in advance?", a: "Yes. We share a monthly calendar for your approval before publishing anything." },
      { q: "Do you handle comments and DMs?", a: "Community management is included — we respond, qualify enquiries and escalate hot leads." },
      { q: "How long until I see results?", a: "Engagement typically improves within 30–45 days; meaningful follower and lead growth takes 3–6 months of consistency." },
      { q: "Do you run paid social campaigns too?", a: "Yes, organic and paid are tightly integrated for compounding growth." },
      { q: "Can you work with our existing brand guidelines?", a: "Absolutely. We adapt to your guidelines or build a fresh visual identity for social." },
      { q: "What reporting do I receive?", a: "A monthly performance report covering reach, engagement, follower growth, top content and next-month plan." },
      { q: "Which industries do you work with?", a: "Startups, local businesses, e-commerce brands, service businesses, and growing enterprises across India." },
    ],
  },
  {
    slug: "seo-local-seo",
    title: "SEO & Local SEO",
    short: "Rank higher on Google and dominate local search.",
    icon: Search,
    category: "SEO",
    tagline: "SEO that compounds — every single month.",
    headline: "SEO Strategies That Improve Rankings, Visibility & Traffic",
    overview:
      "At Optivo Solutions, we provide result-driven SEO and Local SEO services designed to improve Google rankings, increase organic website traffic, strengthen online visibility, and help businesses generate long-term digital growth.",
    overviewExtra:
      "As a leading SEO agency, we optimize websites for traditional SEO and modern Answer Engine Optimization (AEO) to improve discoverability across Google Search, AI-driven search experiences, voice search, and local search results.",
    included: [
      "Technical SEO Optimization",
      "On-Page SEO",
      "Local SEO Services",
      "Google Business Profile Optimization",
      "Website SEO Audit",
      "Keyword Research & Strategy",
      "Competitor Analysis",
      "SEO Content Optimization",
      "Meta Tags & Schema Optimization",
      "Google Maps Ranking Optimization",
      "SEO Performance Tracking & Reporting",
      "AI Search & AEO Optimization",
    ],
    why: "Organic search delivers the highest ROI of any channel. The right SEO foundation turns your website into a 24/7 acquisition engine.",
    benefits: [
      { title: "Higher Google Rankings", desc: "Page 1 visibility for keywords that actually convert." },
      { title: "Quality Organic Traffic", desc: "Targeted visitors with real purchase intent." },
      { title: "Local Market Dominance", desc: "Win Google Maps and the local 3-pack in your service area." },
      { title: "Long-Term Authority", desc: "Build domain trust that compounds year after year." },
      { title: "Lower Customer Acquisition Cost", desc: "Reduce dependence on paid ads as organic compounds." },
      { title: "AI Search Visibility", desc: "Get cited by ChatGPT, Perplexity, Gemini and voice search." },
    ],
    whyChoose: standardWhyChoose,
    process: standardProcess,
    stats: [
      { label: "Avg. Traffic Lift", value: 312, suffix: "%" },
      { label: "Keywords Ranked", value: 1800, suffix: "+" },
      { label: "Client Retention", value: 96, suffix: "%" },
    ],
    faqs: [
      { q: "How long until I see SEO results?", a: "Most clients see meaningful movement in 3 months and significant lift in 6–9 months." },
      { q: "Do you guarantee #1 rankings?", a: "No ethical SEO agency does. We guarantee process, transparency and consistent measurable growth." },
      { q: "What's the difference between SEO and Local SEO?", a: "SEO improves overall organic visibility; Local SEO focuses on Google Maps, local pack and geo-targeted searches." },
      { q: "Do you do technical SEO?", a: "Yes — Core Web Vitals, crawlability, indexation, schema, internal linking and site architecture." },
      { q: "Will I own the SEO work you do?", a: "Yes. Every audit, content asset and optimization stays with you forever." },
      { q: "Do you build backlinks?", a: "Yes, through digital PR, guest contributions, niche edits and citation building — all white-hat." },
      { q: "Can you fix an existing site or do you only rebuild?", a: "We optimize what you have first. Rebuilds are only recommended when truly necessary." },
      { q: "Do you report monthly?", a: "Yes — rankings, traffic, conversions, technical health and next-month roadmap." },
      { q: "What is AEO and do I need it?", a: "Answer Engine Optimization helps AI-driven search engines surface your brand. It is increasingly critical alongside traditional SEO." },
      { q: "Which industries do you work with?", a: "Startups, local businesses, e-commerce, service businesses and growing enterprises across multiple verticals." },
    ],
  },
  {
    slug: "website-development",
    title: "Website Development",
    short: "Fast, beautiful, conversion-built websites.",
    icon: Code2,
    category: "Web",
    tagline: "Websites that load fast and sell faster.",
    headline: "Modern Websites Designed For Growth & Conversion",
    overview:
      "At Optivo Solutions, we create modern, responsive and SEO-friendly websites designed to improve online visibility, strengthen brand credibility, enhance user experience and generate quality business leads.",
    overviewExtra:
      "As a professional website development company, we build conversion-focused business websites that combine clean design, fast performance, mobile responsiveness and SEO optimization to help businesses grow digitally.",
    included: [
      "Business Website Development",
      "Responsive Website Design",
      "SEO-Friendly Website Development",
      "Landing Page Design",
      "UI/UX Focused Web Design",
      "WordPress Website Development",
      "Website Speed Optimization",
      "Lead Generation Website Setup",
      "Mobile Optimization",
      "Website Content Structuring",
      "Conversion-Focused Design Strategy",
      "Website Maintenance & Support",
    ],
    why: "Your website is your hardest-working salesperson. A slow, generic site costs you leads every single day.",
    benefits: [
      { title: "Blazing Performance", desc: "Sub-2-second load times with Core Web Vitals in the green." },
      { title: "Mobile-First Design", desc: "Built for the 95%+ of users browsing on mobile." },
      { title: "SEO Foundation", desc: "Optimized structure, schema and content from day one." },
      { title: "Higher Conversions", desc: "Every section engineered to move visitors toward action." },
      { title: "Easy Content Management", desc: "Edit content without needing a developer." },
      { title: "Secure & Scalable", desc: "Best-in-class hosting, SSL and ongoing support." },
    ],
    whyChoose: standardWhyChoose,
    process: standardProcess,
    stats: [
      { label: "Sites Launched", value: 180, suffix: "+" },
      { label: "Avg. PageSpeed", value: 97, suffix: "/100" },
      { label: "Conversion Lift", value: 68, suffix: "%" },
    ],
    faqs: [
      { q: "How long does a website take to build?", a: "A marketing website takes 3–5 weeks; e-commerce stores typically 6–10 weeks depending on scope." },
      { q: "Do you handle hosting and domains?", a: "Yes — we offer managed hosting with global CDN, SSL and 99.9% uptime SLA." },
      { q: "Will my website be mobile-friendly?", a: "Yes. Every site is built mobile-first and tested on all major devices and breakpoints." },
      { q: "Can I update the website myself?", a: "Yes. We deliver a clean CMS so non-technical team members can update content easily." },
      { q: "Do you build e-commerce stores?", a: "Yes — Shopify, WooCommerce, custom-coded stores and headless stacks." },
      { q: "Is SEO included?", a: "On-page SEO foundations are built in. Ongoing SEO is offered as a separate retainer." },
      { q: "Will I own the website?", a: "Yes. Full code, assets and credentials are handed over." },
      { q: "Do you redesign existing websites?", a: "Yes, we audit and modernize existing sites or build from scratch — whichever serves you best." },
      { q: "Do you offer ongoing maintenance?", a: "Yes. Care plans cover updates, backups, security and small content changes." },
      { q: "How much does a website cost?", a: "Marketing sites start from ₹45,000; complex e-commerce and custom builds are quoted per scope." },
    ],
  },
  {
    slug: "meta-google-ads",
    title: "Meta Ads & Google Ads Management",
    short: "High-performance paid advertising that drives real results.",
    icon: Target,
    category: "Ads",
    tagline: "Paid media that pays you back.",
    headline: "High-Performance Paid Advertising Strategies That Drive Results",
    overview:
      "At Optivo Solutions, we create data-driven Meta Ads and Google Ads campaigns designed to improve online visibility, generate high-quality leads, increase conversions and maximize return on investment (ROI).",
    overviewExtra:
      "As a performance-focused digital advertising agency, we help businesses reach the right audience through strategic audience targeting, ad optimization, remarketing campaigns and conversion-focused advertising strategies across Meta and Google platforms.",
    included: [
      "Meta Ads Campaign Management",
      "Facebook & Instagram Advertising",
      "Google Search Ads",
      "Google Display Ads",
      "YouTube Ads Campaigns",
      "Audience Research & Targeting",
      "Ad Copywriting & Creative Strategy",
      "Retargeting & Remarketing Campaigns",
      "Conversion Tracking Setup",
      "ROI Optimization",
      "Campaign Performance Reporting",
      "Lead Generation Ad Campaigns",
    ],
    why: "Paid media is the fastest path to qualified leads. Done right, every rupee is measured. Done wrong, every rupee is wasted — we make sure it's the former.",
    benefits: [
      { title: "Immediate Lead Flow", desc: "Qualified traffic from day one of campaign launch." },
      { title: "ROAS-Focused", desc: "Optimized for revenue and pipeline, not vanity clicks." },
      { title: "Full-Funnel Strategy", desc: "Cold, warm and retargeting layers working together." },
      { title: "Creative That Converts", desc: "Scroll-stopping ads engineered for performance." },
      { title: "Conversion Tracking", desc: "Server-side tracking that works post-iOS." },
      { title: "Transparent Reporting", desc: "Weekly dashboards — you always know where your money goes." },
    ],
    whyChoose: standardWhyChoose,
    process: standardProcess,
    stats: [
      { label: "Avg. ROAS", value: 6, suffix: "x" },
      { label: "Lower CPL", value: 42, suffix: "%" },
      { label: "Campaigns Run", value: 480, suffix: "+" },
    ],
    faqs: [
      { q: "What's the minimum ad budget?", a: "We recommend a minimum of ₹25,000/month for meaningful data and optimization." },
      { q: "Who owns the ad account?", a: "You do — always. We manage it and you keep all data and access." },
      { q: "Do you create the ad creatives?", a: "Yes — static, motion graphics, UGC-style videos and full edits done in-house." },
      { q: "How quickly will I see results?", a: "Search Ads typically deliver leads in week one; Meta Ads need 2–3 weeks of optimization to hit stride." },
      { q: "Do you handle landing pages too?", a: "Yes. We design and build conversion-optimized landing pages for each campaign." },
      { q: "What platforms do you cover?", a: "Google Search, Display, Shopping, YouTube, Performance Max, Facebook, Instagram and Messenger Ads." },
      { q: "How do you measure success?", a: "By cost-per-lead, ROAS, conversion rate, and pipeline contribution — never by impressions alone." },
      { q: "Will you set up conversion tracking?", a: "Yes — including Google Tag Manager, GA4, Meta Pixel and server-side Conversion API." },
      { q: "Can you scale my existing campaigns?", a: "Yes. We audit, restructure and scale profitably without losing efficiency." },
      { q: "Do I get weekly reports?", a: "Yes — plus a Slack/WhatsApp channel for daily questions and quick decisions." },
    ],
  },
  {
    slug: "content-branding",
    title: "Content Creation & Branding",
    short: "Brands that feel premium. Content that converts.",
    icon: Sparkles,
    category: "Branding",
    tagline: "Strategic branding & high-converting content.",
    headline: "Creative Branding & Content Strategies That Build Strong Brand Identity",
    overview:
      "At Optivo Solutions, we create impactful branding and content marketing strategies that help businesses strengthen brand identity, improve audience engagement and build long-term customer trust.",
    overviewExtra:
      "As a creative branding and content marketing agency, we focus on storytelling, visual identity, strategic communication and performance-focused content designed to improve online presence and brand recognition.",
    included: [
      "Brand Strategy Development",
      "Content Marketing Strategy",
      "Creative Post Designing",
      "Reels & Video Content Creation",
      "Copywriting & Content Writing",
      "Brand Identity Design",
      "Social Media Creative Production",
      "Marketing Campaign Concepts",
      "Brand Storytelling",
      "Graphic Design Solutions",
      "Product Branding",
      "Content Calendar Planning",
    ],
    why: "In a noisy market, branding is the moat. Great content is what fills it. We build both with strategic intent.",
    benefits: [
      { title: "Premium Brand Identity", desc: "Logo, type, color and visual system that signal quality." },
      { title: "Consistent Storytelling", desc: "One brand voice across every customer touchpoint." },
      { title: "Higher Recall", desc: "Become instantly recognizable in your category." },
      { title: "Content That Earns Attention", desc: "Reels, posts and videos engineered to convert." },
      { title: "Stronger Trust", desc: "Premium branding signals premium service and product." },
      { title: "Scalable Asset Library", desc: "Templates and guidelines your team can use forever." },
    ],
    whyChoose: standardWhyChoose,
    process: standardProcess,
    stats: [
      { label: "Brands Built", value: 70, suffix: "+" },
      { label: "Videos Produced", value: 900, suffix: "+" },
      { label: "Avg. Brand Lift", value: 3, suffix: ".2x" },
    ],
    faqs: [
      { q: "Do you do logos only?", a: "We can — but you'll get far more value from a complete brand identity system." },
      { q: "Will I get brand guidelines?", a: "Yes. Every brand project ships with a usage guide covering logo, type, color and tone." },
      { q: "Do you handle photography and video?", a: "Yes — product, lifestyle, founder shoots, reels and brand films, in-studio or on-location." },
      { q: "How long does branding take?", a: "Identity systems typically take 3–5 weeks; full brand strategy + identity 6–8 weeks." },
      { q: "Can you refresh an existing brand?", a: "Yes — brand audits and refreshes are a core part of what we do." },
      { q: "Do you write content too?", a: "Yes — web copy, blog articles, ad copy, scripts, email and social content." },
      { q: "Do you create monthly content?", a: "Yes. Monthly content retainers cover design, video, copy and publishing." },
      { q: "Will my brand stand out?", a: "That is the goal of every engagement — distinctive, ownable and on-strategy." },
      { q: "Do you work with startups?", a: "Yes. We have packages designed specifically for early-stage brands." },
      { q: "What deliverables do I receive?", a: "Brand strategy doc, identity files, templates, guidelines and a full content asset library." },
    ],
  },
  {
    slug: "lead-generation",
    title: "Lead Generation Campaigns",
    short: "Strategic campaigns that fill your pipeline with qualified buyers.",
    icon: Megaphone,
    category: "Growth",
    tagline: "Performance-driven lead generation.",
    headline: "Lead Generation Strategies Focused On Business Growth & Conversions",
    overview:
      "At Optivo Solutions, we create strategic lead generation campaigns designed to attract high-quality customers, improve conversion rates and generate measurable business growth through performance-driven digital marketing solutions.",
    overviewExtra:
      "Our lead generation strategies combine SEO, Meta Ads, Google Ads, landing page optimization and audience targeting to help businesses generate relevant inquiries and maximize customer acquisition.",
    included: [
      "Lead Generation Campaign Setup",
      "Meta Lead Ads",
      "Google Lead Campaigns",
      "Landing Page Optimization",
      "Conversion Funnel Strategy",
      "CRM Integration Support",
      "Audience Research & Retargeting",
      "WhatsApp Lead Campaigns",
      "Sales Funnel Optimization",
      "Performance Tracking & Reporting",
      "Customer Acquisition Strategy",
      "Conversion Optimization",
    ],
    why: "Growth is a function of qualified pipeline. We build the systems and campaigns that produce predictable, scalable lead flow.",
    benefits: [
      { title: "Predictable Pipeline", desc: "Repeatable systems that produce leads every month." },
      { title: "Higher Lead Quality", desc: "Filters, qualification and targeting that bring real buyers." },
      { title: "Lower Cost Per Lead", desc: "Funnel optimization to drop CPL by 30–60%." },
      { title: "Faster Sales Cycles", desc: "WhatsApp and CRM workflows that respond instantly." },
      { title: "Multi-Channel Reach", desc: "SEO, Meta, Google and WhatsApp working as one funnel." },
      { title: "Clear ROI", desc: "Full attribution from ad spend to revenue." },
    ],
    whyChoose: standardWhyChoose,
    process: standardProcess,
    stats: [
      { label: "Leads Generated", value: 1200000, suffix: "+" },
      { label: "Avg. CPL Drop", value: 38, suffix: "%" },
      { label: "Funnels Built", value: 320, suffix: "+" },
    ],
    faqs: [
      { q: "How many leads can I expect?", a: "Volume depends on industry, budget and offer — we set realistic monthly targets before launch." },
      { q: "What's the minimum budget?", a: "Typically ₹30,000/month in ad spend plus the management retainer for meaningful results." },
      { q: "Do you guarantee lead quality?", a: "We don't guarantee specific outcomes, but we engineer qualification filters and optimize ruthlessly for quality." },
      { q: "Can you integrate with my CRM?", a: "Yes — Zoho, HubSpot, Salesforce, Pipedrive and most major CRMs." },
      { q: "Do you build the landing pages?", a: "Yes. Every campaign gets a conversion-optimized landing page." },
      { q: "What channels do you use?", a: "Meta Lead Ads, Google Lead Forms, search ads, SEO and WhatsApp Click-to-Chat campaigns." },
      { q: "How quickly do leads start coming in?", a: "Most campaigns generate leads within 48–72 hours of launch." },
      { q: "Do you send leads via WhatsApp instantly?", a: "Yes — instant WhatsApp notifications and automated first responses are included." },
      { q: "What reporting do I get?", a: "Daily lead counts, weekly cost-per-lead and monthly ROI dashboards." },
      { q: "Which industries do you serve?", a: "Real estate, education, professional services, e-commerce, local businesses and B2B." },
    ],
  },
  {
    slug: "google-business-profile",
    title: "Google Business Profile Optimization",
    short: "Win Google Maps, the local 3-pack and customer trust.",
    icon: MapPin,
    category: "Local",
    tagline: "Local visibility, calls and direction requests — on autopilot.",
    headline: "Google Profile Optimization That Improves Local Visibility & Trust",
    overview:
      "At Optivo Solutions, we help businesses improve their Google Business Profile visibility, local search rankings, Google Maps presence and customer trust through strategic local SEO optimization.",
    overviewExtra:
      "Our Google Business Profile optimization services are designed to help businesses appear in relevant local searches, attract nearby customers and improve online credibility.",
    included: [
      "Google Business Profile Setup",
      "Google Maps Optimization",
      "Local SEO Optimization",
      "Business Information Optimization",
      "Review & Reputation Management",
      "Google Profile Content Updates",
      "Service & Product Listing Optimization",
      "Local Keyword Optimization",
      "Geo-Targeted Visibility Strategy",
      "Business Category Optimization",
      "Monthly GBP Monitoring",
      "Local Search Performance Reporting",
    ],
    why: "For local businesses, the Google Map pack drives more calls and footfall than the rest of the website combined. A fully optimised profile is the single highest-ROI local asset.",
    benefits: [
      { title: "Top-3 Map Pack Visibility", desc: "Show up first when nearby customers search." },
      { title: "More Calls & Directions", desc: "Direct conversion actions straight from search." },
      { title: "Stronger Customer Trust", desc: "Reviews, photos and posts that reassure buyers." },
      { title: "Local Keyword Rankings", desc: "Win city, neighborhood and pin-code searches." },
      { title: "Reputation Management", desc: "Generate, respond to and recover from reviews." },
      { title: "Monthly Optimization", desc: "Fresh posts, photos and updates that keep ranking." },
    ],
    whyChoose: standardWhyChoose,
    process: standardProcess,
    stats: [
      { label: "Map Ranking Lift", value: 4, suffix: "x" },
      { label: "Calls / Month Avg.", value: 180, suffix: "+" },
      { label: "Profiles Managed", value: 220, suffix: "+" },
    ],
    faqs: [
      { q: "How long until I rank in the local 3-pack?", a: "Most clients see top-3 movement within 60–120 days for moderate-competition keywords." },
      { q: "Do I need a physical address?", a: "Yes — Google requires a verifiable business address or service area for profile approval." },
      { q: "What if my profile is suspended?", a: "We handle reinstatement appeals and recovery for suspended profiles." },
      { q: "Can you manage reviews?", a: "Yes — generation campaigns, monitoring, responses and reputation defence." },
      { q: "How often do you update the profile?", a: "Posts go up weekly; photos, services and Q&A are refreshed monthly." },
      { q: "Can you optimize multiple locations?", a: "Yes — multi-location and franchise GBP management is a specialty." },
      { q: "Will this work with SEO?", a: "Yes. GBP optimization is most powerful when paired with on-site local SEO." },
      { q: "What reporting do I get?", a: "Monthly reports on rankings, calls, direction requests, photo views and review performance." },
      { q: "Do you respond to reviews on my behalf?", a: "Yes, with approved templates and your brand voice — including handling negative reviews professionally." },
      { q: "How is this different from regular SEO?", a: "Local SEO and GBP focus on Maps and local pack rankings; traditional SEO targets organic web results." },
    ],
  },
  {
    slug: "aeo-geo-optimization",
    title: "AI & Search Optimization",
    short: "Be discovered across Google, ChatGPT, Perplexity & voice search.",
    icon: Brain,
    category: "SEO",
    tagline: "Be the answer AI search picks.",
    headline: "AI & Search Optimization For Future-Ready Digital Visibility",
    overview:
      "At Optivo Solutions, we help businesses optimize their digital presence for modern AI-driven search experiences through Answer Engine Optimization (AEO) and Generative Engine Optimization (GEO) strategies.",
    overviewExtra:
      "Our optimization strategies are designed to improve discoverability across Google Search, AI search engines (ChatGPT, Perplexity, Gemini), voice search, local search results and generative search experiences.",
    included: [
      "Answer Engine Optimization (AEO)",
      "Generative Engine Optimization (GEO)",
      "AI Search Optimization",
      "ChatGPT & Perplexity Visibility",
      "Google AI Overview Optimization",
      "Conversational Search Optimization",
      "Structured FAQ Development",
      "Schema Markup Optimization",
      "Voice Search Optimization",
      "Search Intent Content Strategy",
      "AI-Friendly Website Structuring",
      "Localized Content Optimization",
      "Google Discover Optimization",
      "Entity & Topical Authority Building",
    ],
    why: "Search is shifting from blue links to AI-generated answers. Brands that optimize for AEO and GEO today own visibility tomorrow — those that don't will disappear from the conversation entirely.",
    benefits: [
      { title: "Be Cited By AI", desc: "Show up as a source inside ChatGPT, Perplexity, Gemini and Google AI Overviews." },
      { title: "Voice Search Wins", desc: "Optimized for natural-language, conversational queries." },
      { title: "Featured Snippets", desc: "Capture position zero on traditional Google search." },
      { title: "Structured Authority", desc: "Schema and entity SEO that machines understand instantly." },
      { title: "Topical Authority", desc: "Become the recognized expert in your category." },
      { title: "Future-Proof Visibility", desc: "Rank across every modern surface — not just the 10 blue links." },
    ],
    whyChoose: standardWhyChoose,
    process: standardProcess,
    stats: [
      { label: "AI Citations Earned", value: 320, suffix: "+" },
      { label: "Snippet Wins", value: 180, suffix: "+" },
      { label: "Voice Queries Ranked", value: 140, suffix: "+" },
    ],
    faqs: [
      { q: "What is AEO?", a: "Answer Engine Optimization structures your content so AI-driven answer engines like ChatGPT, Perplexity and Google's AI Overview can extract and cite it." },
      { q: "What is GEO?", a: "Generative Engine Optimization is the practice of optimizing your brand and content to appear inside AI-generated responses and summaries across modern search platforms." },
      { q: "Is AEO the same as SEO?", a: "No. SEO targets ranked links; AEO targets being the cited answer. They overlap but require different content and schema strategies." },
      { q: "How does Optivo get my brand into ChatGPT?", a: "Through topical authority, structured content, schema, citations on trusted sources and entity-aware writing that LLMs surface." },
      { q: "Does AEO help voice search too?", a: "Yes — voice assistants pull from the same answer-friendly content AEO produces." },
      { q: "How long does AEO take?", a: "Initial AI citations can appear in 60–90 days; durable authority takes 4–6 months of consistent work." },
      { q: "What is schema markup?", a: "Structured data (JSON-LD) that tells search engines and AI exactly what your content is — Article, FAQ, Product, Organization, etc." },
      { q: "Do I still need traditional SEO?", a: "Yes. AEO and SEO are complementary — both are needed for full-spectrum visibility." },
      { q: "Will AEO work for local businesses?", a: "Yes — local intent queries are increasingly answered by AI, and GEO ensures you're surfaced." },
      { q: "Can you optimize my existing content for AEO?", a: "Yes. We audit and restructure existing pages with FAQ blocks, schema and answer-first writing." },
      { q: "Do you build AI-friendly site architecture?", a: "Yes — clear entity hierarchy, internal linking, schema and crawlable structure for both Google and LLM crawlers." },
      { q: "How do you measure AEO success?", a: "AI citation tracking, snippet ownership, voice-query rankings, branded mentions in LLM responses and organic AI-driven traffic." },
    ],
  },
  {
    slug: "ecommerce-marketing",
    title: "E-Commerce Marketing",
    short: "More carts. More revenue. Lower CAC.",
    icon: ShoppingBag,
    category: "E-commerce",
    tagline: "Full-funnel growth for online stores.",
    headline: "E-Commerce Marketing Strategies That Increase Sales & Visibility",
    overview:
      "At Optivo Solutions, we help e-commerce brands improve online visibility, increase website traffic, optimize conversions and drive higher product sales through strategic digital marketing solutions.",
    overviewExtra:
      "Our e-commerce marketing strategies combine SEO, performance marketing, marketplace optimization, social media marketing and conversion-focused advertising to help brands scale effectively.",
    included: [
      "E-Commerce SEO",
      "Marketplace Marketing (Amazon, Flipkart)",
      "Product Advertising Campaigns",
      "Google Shopping Ads",
      "Meta Ads For E-Commerce",
      "Conversion Rate Optimization",
      "Product Launch Campaigns",
      "Cart Abandonment Retargeting",
      "Sales Funnel Optimization",
      "Product Page Optimization",
      "Performance Analytics & Reporting",
      "E-Commerce Growth Strategy",
    ],
    why: "E-commerce is brutal: thin margins, rising ad costs and constant CAC pressure. We win by treating every channel as one connected revenue funnel.",
    benefits: [
      { title: "Higher Revenue Per Visitor", desc: "CRO and funnel optimization compound every other channel." },
      { title: "Lower Customer Acquisition Cost", desc: "Smart targeting and retargeting that protect margin." },
      { title: "Repeat Purchases", desc: "Email, SMS and WhatsApp retention flows that build LTV." },
      { title: "Marketplace Visibility", desc: "Win on Amazon, Flipkart and your own store simultaneously." },
      { title: "Product Discovery", desc: "Google Shopping and Meta catalog ads that scale efficiently." },
      { title: "Profit-First Reporting", desc: "Track ROAS, MER and contribution margin, not just spend." },
    ],
    whyChoose: standardWhyChoose,
    process: standardProcess,
    stats: [
      { label: "Avg. Revenue Lift", value: 184, suffix: "%" },
      { label: "Email Revenue Share", value: 28, suffix: "%" },
      { label: "Stores Scaled", value: 90, suffix: "+" },
    ],
    faqs: [
      { q: "Do you work with Shopify and WooCommerce?", a: "Yes — plus Magento, headless stacks and custom storefronts." },
      { q: "Can you manage Amazon and Flipkart?", a: "Yes — listings, advertising, A+ content and review management on major marketplaces." },
      { q: "Do you handle email and SMS too?", a: "Yes — Klaviyo, Mailchimp and Brevo expertise for welcome, abandoned cart, post-purchase and win-back flows." },
      { q: "Will you optimize my product pages?", a: "Yes — copy, imagery, schema, reviews and checkout flow are all part of CRO." },
      { q: "What ad spend do I need?", a: "₹50,000+/month in ad spend is typical to see meaningful scale in e-commerce." },
      { q: "Do you help with product launches?", a: "Yes — launch strategy, creative, pre-launch lists and paid amplification." },
      { q: "How do you measure success?", a: "ROAS, MER, contribution margin, AOV and customer lifetime value — not just topline revenue." },
      { q: "Can you set up Google Shopping?", a: "Yes — feed creation, optimization, Merchant Center setup and Performance Max campaigns." },
      { q: "Do you offer CRO audits?", a: "Yes. CRO audits identify the biggest revenue leaks in your funnel." },
      { q: "How quickly will I see growth?", a: "Acquisition campaigns generate sales within days; retention systems compound over 60–90 days." },
    ],
  },
  {
    slug: "pr-influencer-marketing",
    title: "PR, Influencer Marketing & Brand Visibility Solutions",
    short: "Build awareness, credibility and market presence at scale.",
    icon: Star,
    category: "Branding",
    tagline: "PR, creators, production and offline — all under one roof.",
    headline: "PR, Influencer Marketing & Brand Visibility Solutions",
    overview:
      "Build Brand Awareness, Credibility and Market Presence through strategic PR, influencer collaborations, creative content production and offline advertising campaigns.",
    overviewExtra:
      "At Optivo Solutions, we help businesses increase visibility and audience engagement through integrated PR, influencer marketing, creative production and offline branding solutions designed to strengthen brand positioning, improve market reach and create lasting customer impact.",
    included: [
      "PR Campaign Planning",
      "Press Releases & Media Outreach",
      "Media Coverage & Brand Features",
      "Brand Reputation Management",
      "Product & Service Launch Campaigns",
      "Influencer & Creator Collaborations",
      "Instagram & YouTube Campaigns",
      "UGC Content Campaigns",
      "Brand Partnerships",
      "Influencer Campaign Management & Reporting",
      "Product Photography",
      "Brand Promotional Videos",
      "Corporate Shoots & Drone Videography",
      "Reels & Short-Form Video Production",
      "Editing & Post-Production",
      "Newspaper & Print Advertising",
      "Billboard & Outdoor Advertising",
      "Event Promotions & Local Market Branding",
      "Brochures, Catalogues & Corporate Profiles",
      "Standees, Flyers & Promotional Materials",
    ],
    why: "Modern brand-building requires more than ads. Earned media, creator trust, premium production and offline visibility together create the kind of presence that becomes unavoidable.",
    benefits: [
      { title: "Earned Media Coverage", desc: "Featured in trusted publications your customers already read." },
      { title: "Creator Credibility", desc: "Authentic endorsement from influencers your audience trusts." },
      { title: "Premium Content Library", desc: "Photography, video and reels you'll use across every channel." },
      { title: "Offline Brand Presence", desc: "Outdoor, print and event branding that builds local recall." },
      { title: "Launch Momentum", desc: "Integrated 360° campaigns that turn launches into events." },
      { title: "Reputation Protection", desc: "Proactive PR and review strategy that protects brand equity." },
    ],
    whyChoose: standardWhyChoose,
    process: standardProcess,
    stats: [
      { label: "Media Placements", value: 320, suffix: "+" },
      { label: "Creators Activated", value: 850, suffix: "+" },
      { label: "Production Projects", value: 400, suffix: "+" },
    ],
    faqs: [
      { q: "Do you handle PR pitching directly?", a: "Yes. We pitch to journalists, editors and producers across digital, print and broadcast media." },
      { q: "Can you guarantee media coverage?", a: "No ethical PR firm guarantees placements. We guarantee professional outreach, pitch quality and consistent activity." },
      { q: "How do you choose influencers?", a: "By audience overlap, engagement quality, content fit and historical campaign performance — never by follower count alone." },
      { q: "Do you handle creator contracts and payments?", a: "Yes — sourcing, negotiation, briefing, content approval, payment and reporting are all managed end-to-end." },
      { q: "What kind of video production do you do?", a: "Product films, brand stories, ads, reels, founder shoots, event coverage and drone videography." },
      { q: "Do you offer photography services?", a: "Yes — product, lifestyle, e-commerce, corporate and editorial photography." },
      { q: "Can you run outdoor and print campaigns?", a: "Yes — billboard, hoarding, newspaper, magazine and local event branding across India." },
      { q: "Do you design printed materials?", a: "Yes — brochures, catalogues, flyers, standees, corporate profiles and promotional materials." },
      { q: "Do you handle UGC campaigns?", a: "Yes — sourcing creators, briefing for authentic content and managing usage rights." },
      { q: "Can you run integrated campaigns combining PR, influencers and ads?", a: "Yes — and the compounding effect of running them together is exactly where this service shines." },
    ],
  },
];

export const getService = (slug: string) => services.find((s) => s.slug === slug);
